### ISSUE TITLE
Modify generic numbers and Strings

### ISSUE THREAD

**Issue by JeyP91** [openhab/openhab-mycroft#44]
Hey @mortommy,

thanks for your amazing work! Your skill is working perfectly in my setup.

I just have a small feature request:
Could it be possible to change generic numbers and strings?
I would like to control my AV-Receiver and for this I have numbers to modify (for example volume) and strings (for example the input source).

Thank you!

**Comment by mortommy** [comment]
Hi, thank you.
In order to pubblish items to mycroft tags are needed and the types of tags are: Lighting, Switchable, Thermostat, CurrentHumidity, CurrentTemperature; the type of the tag is important to establish valid commands (f.i. ON/OFF if it's a switchable type). There's no tags for string, though maybe you can try some workarounds:
- volume: try to tag the item as switchable and use the dim/brighten voice commands, it'll send numbers to the item (from 0 to 100).
- input source: you can use a proxy item tagged as switchable to make it available to mycroft and by a rule send the string to the item AV-Receiver (f.i. "Hey Mycroft, put ON input1", when input1 goes ON a rule can be triggered and send the string command to the AV-Receiver).
Hope it helps.

**Comment by JeyP91** [comment]
Hi @mortommy,

thanks for your hint, this will work for sure! :)
But maybe you can consider this request for the future if it is possible at all.
Thanks again for your work!

**Comment by mortommy** [comment]
Thank you to you.
