### ISSUE TITLE
Issue with one string when translating to spanish

### ISSUE THREAD

**Issue by adocampo** [openhab/openhab-mycroft#57]
When translatting via pootle the sentence:

`(what is|what's) (?P<Item>.*) (?P<RequestType>status|temperature|humidity|adjusted to|regulated to|tuned to)`

I need to change the order of `(?P<Item>.*)` with `(?P<RequestType>` like this

`(qué|a qué|cuál) (?P<RequestType>estado|temperatura|humedad|ajustes) (está|está el|está la) (?P<Item>.*)`

But I can't. It complains about XML tags. It's weird because I've exchanged the order before, so I don't know if I'm doing something wrong or you expect the order just like this.

**Comment by mortommy** [comment]
Hi,
there's no check about the order. 
In this kind of command it's needed to check the type of status requested: temperature, humidity, termostat or just an item status; the codes has a case on RequestType and checks the values for the different languages, since Spanish it is not added yet I expect the command is intended as "get the termostat status" and maybe you get an error.
Usually when a new language is added I make the changes in that part of codes.
Currently there's another PR adding Spanish.

**Comment by adocampo** [comment]
Well, so I'll wait until the merge and try back when done and let you know the result.

**Comment by krisgesling** [comment]
The XML error is a Pootle check. It's meant to ensure that all tags in the source string are also included in the translated string, however it's failing when the order of those is changed. 

I can manually override this error if it shows up, I'm assuming it's this string: https://translate.mycroft.ai/projects/mycroft-skills/translate/openhab-mycroft-es_LM.po

Can you set the translation to what it should be and I'll override the XML error.

**Comment by mortommy** [comment]
Added Spanish. I was waiting for a fix but the translation was made by an automation. I made a manual fix.
